import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * robots.txt — generated by Next.js App Router.
 *
 * Strategy:
 * - Allow standard search crawlers (Googlebot, Bingbot)
 * - Allow modern AI crawlers (GPTBot, ChatGPT-User, ClaudeBot, PerplexityBot,
 *   Google-Extended, Applebot-Extended) so we appear in AI overview answers
 * - Disallow internal/utility paths
 * - Point to the sitemap for discovery
 */
export default function robots(): MetadataRoute.Robots {
  const aiBots = [
    "GPTBot",
    "ChatGPT-User",
    "OAI-SearchBot",
    "ClaudeBot",
    "Claude-Web",
    "anthropic-ai",
    "PerplexityBot",
    "Perplexity-User",
    "Google-Extended",
    "Applebot-Extended",
    "FacebookBot",
    "Meta-ExternalAgent",
    "Bytespider",
    "Amazonbot",
    "cohere-ai",
    "YouBot",
  ];

  return {
    rules: [
      // Default rule: everything allowed except admin/api/utility paths
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/", "/admin/"],
      },
      // Explicit AI-bot allowlist (some bots only respect their own UA-line)
      ...aiBots.map((bot) => ({
        userAgent: bot,
        allow: "/",
      })),
    ],
    sitemap: `${site.url}/sitemap.xml`,
    host: site.url,
  };
}
