import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * sitemap.xml — generated by Next.js App Router.
 *
 * Strategy:
 * - Homepage: priority 1.0, weekly
 * - Two pillar pages: priority 0.9, monthly
 * - Service pages: priority 0.8, monthly
 * - Company pages (about, contact, careers): priority 0.7, monthly
 * - Founder pages: priority 0.6, monthly
 * - Legal pages: priority 0.3, yearly
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const url = (path: string) => `${site.url}${path}`;

  const homepage: MetadataRoute.Sitemap[number] = {
    url: url("/"),
    lastModified: now,
    changeFrequency: "weekly",
    priority: 1.0,
  };

  const pillarPages: string[] = [
    "/chef-inhuren-hotel-amsterdam/",
    "/payroll-chef-inhuren/",
  ];

  const servicePages: string[] = [
    "/horeca-personeel-inhuren/",
    "/chef-inhuren/",
    "/kok-inhuren-amsterdam/",
    "/hotel-personeel-inhuren/",
    "/horeca-uitzendbureau-amsterdam/",
    "/bediening-inhuren/",
    "/tijdelijk-horeca-personeel/",
    "/premium-kok-inhuren-hotel-restaurant/",
    "/horeca-freelancer/",
    "/catering-personeel-inhuren/",
    "/evenement-personeel-inhuren/",
    "/hospitality-recruitment/",
    "/keuken-personeel-inhuren/",
    "/restaurant-personeel-inhuren/",
    "/horeca-personeel-den-haag/",
    "/horeca-personeel-rotterdam/",
    "/werken-als-chef-kok-tophotels-restaurants/",
  ];

  const companyPages: string[] = [
    "/our-offer/",
    "/who-we-are/",
    "/work-with-us/",
    "/contact-us/",
    "/over-chef-and-serve-horeca-uitzendbureau-amsterdam/",
  ];

  const founderPages: string[] = [
    "/over-maarten/",
    "/ik-ben-maarten-chef-and-serve/",
  ];

  const legalPages: string[] = [
    "/privacybeleid/",
    "/algemene-voorwaarden/",
  ];

  return [
    homepage,
    ...pillarPages.map((path) => ({
      url: url(path),
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.9,
    })),
    ...servicePages.map((path) => ({
      url: url(path),
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    ...companyPages.map((path) => ({
      url: url(path),
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...founderPages.map((path) => ({
      url: url(path),
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
    ...legalPages.map((path) => ({
      url: url(path),
      lastModified: now,
      changeFrequency: "yearly" as const,
      priority: 0.3,
    })),
  ];
}
