/**
 * docs/STATE.generated.md — every COUNT and INVENTORY in the documentation set.
 *
 * WHY THIS EXISTS
 * Hand-typed counts rot. MEMORY.md claimed 34 (then 48, then 77) AI tools while the registry
 * held 111; it listed 12 enums against 67, ~45 tables against 92, 14 workers against 23, and a
 * migration head six behind. Every one of those was a number a human typed once and nobody
 * re-derived. So: no other document may state a count. They link here, and this file is
 * regenerated by `npm run docs:state`.
 *
 * DESIGN RULE — static analysis only. No DB connection, no env vars, no imports of app code.
 * That keeps it runnable in CI with no secrets and makes it impossible for this script to be
 * the thing that breaks a build.
 *
 *   npx tsx scripts/gen-docs-state.ts          # writes docs/STATE.generated.md
 *   npx tsx scripts/gen-docs-state.ts --check   # exit 1 if the file is out of date (for CI)
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/** Walk up from cwd to the repo root (the dir holding package.json). */
function repoRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "package.json"))) return dir;
    dir = join(dir, "..");
  }
  return process.cwd();
}

const ROOT = repoRoot();
const OUT = join(ROOT, "docs", "STATE.generated.md");

const read = (p: string): string => {
  try {
    return readFileSync(join(ROOT, p), "utf8");
  } catch {
    return "";
  }
};
const ls = (p: string): string[] => {
  try {
    return readdirSync(join(ROOT, p)).sort();
  } catch {
    return [];
  }
};
/** All regex matches of group 1, in file order. */
const all = (src: string, re: RegExp): string[] => [...src.matchAll(re)].map((m) => m[1]);

/* ------------------------------------------------------------------ schema */

function schema() {
  const src = read("src/lib/db/schema.ts");
  const tables = all(src, /=\s*pgTable\(\s*"([^"]+)"/g);
  const enums = all(src, /=\s*pgEnum\(\s*"([^"]+)"/g);
  return { tables, enums };
}

/* -------------------------------------------------------------- migrations */

function migrations() {
  const files = ls("drizzle").filter((f) => /^\d{4}_.*\.sql$/.test(f));
  const manual = ls("drizzle").filter((f) => /^manual_.*\.sql$/.test(f));
  let journal = 0;
  try {
    journal = JSON.parse(read("drizzle/meta/_journal.json")).entries.length;
  } catch {
    /* keep 0 — surfaced as a mismatch below */
  }
  return { head: files.at(-1) ?? "(none)", count: files.length, journal, manual };
}

/* --------------------------------------------------------- scheduled work */

function scheduled() {
  const sup = read("workers/supervisor.ts");
  const jobs = [...sup.matchAll(/\{\s*name:\s*"([^"]+)"\s*,\s*schedule:\s*"([^"]+)"/g)].map(
    (m) => ({ name: m[1], schedule: m[2] }),
  );
  let crons: { path: string; schedule: string }[] = [];
  try {
    crons = (JSON.parse(read("vercel.json")).crons ?? []) as typeof crons;
  } catch {
    /* none */
  }
  // A job registered in BOTH places is triggered twice per window. Today both such routes are
  // idempotent (shift-reminders dedupes per placement+tier, clockout-digest throttles daily), so
  // it is harmless — but it is load-bearing that they STAY idempotent, so surface it.
  const cronNames = crons.map((c) => c.path.split("/").pop());
  const doubled = jobs.filter((j) => cronNames.includes(j.name)).map((j) => j.name);
  return { jobs, crons, doubled };
}

/* ---------------------------------------------------------------- ai tools */

/** Pull `name` + `risk` out of every defineTool({...}) block across the tool files. */
function aiTools() {
  const dir = "src/lib/ai/tools";
  const defs = new Map<string, { risk: string; file: string }>();
  for (const f of ls(dir).filter((f) => /\.tsx?$/.test(f))) {
    const src = read(join(dir, f));
    for (const block of src.split("defineTool(").slice(1)) {
      const head = block.slice(0, 1200);
      const name = head.match(/name:\s*"([^"]+)"/)?.[1];
      const risk = head.match(/risk:\s*"([^"]+)"/)?.[1] ?? "?";
      if (name) defs.set(name, { risk, file: `${dir}/${f}` });
    }
  }

  // Registry membership: which exported consts land in which array.
  const idx = read(`${dir}/index.ts`);
  const owner = (idx.match(/ALL_TOOLS:\s*AnyTool\[\]\s*=\s*\[([\s\S]*?)\n\];/)?.[1] ?? "")
    .split("\n")
    .map((l) => l.replace(/\/\/.*/, "").trim().replace(/,$/, ""))
    .filter((l) => l && /^[A-Za-z_$][\w$]*$/.test(l));

  const portal = read(`${dir}/portal-index.ts`);
  const arr = (name: string) =>
    (portal.match(new RegExp(`${name}:\\s*AnyTool\\[\\]\\s*=\\s*\\[([^\\]]*)\\]`))?.[1] ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

  const byRisk: Record<string, number> = {};
  for (const { risk } of defs.values()) byRisk[risk] = (byRisk[risk] ?? 0) + 1;

  return {
    defined: defs.size,
    owner: owner.length,
    chef: arr("CHEF_TOOLS").length,
    client: arr("CLIENT_TOOLS").length,
    byRisk,
    names: [...defs.keys()].sort(),
  };
}

/* ------------------------------------------------------------------- evals */

function evals() {
  const src = read("scripts/eval-ai.mts");
  const counts: Record<string, number> = {};
  for (const kind of ["GOLDEN", "CHAOS", "MULTI", "SAFETY"]) {
    const body = src.match(new RegExp(`const ${kind}[A-Z_]*:[^=]*=\\s*\\[([\\s\\S]*?)\\n\\];`))?.[1];
    // one case per `id:` key — robust to nested objects and multi-line cases
    counts[kind] = body ? (body.match(/\bid:\s*["'`]/g) ?? []).length : 0;
  }
  const ids = all(src, /\bid:\s*["'`]([^"'`]+)["'`]/g);
  const dupes = [...new Set(ids.filter((v, i) => ids.indexOf(v) !== i))];
  return { counts, total: Object.values(counts).reduce((a, b) => a + b, 0), dupes };
}

/* ------------------------------------------------------------------- flags */

function flags() {
  const env = read("src/lib/env.ts");
  // Declared in the zod schema — typo-safe.
  const declared = all(env, /^\s{2}([A-Z][A-Z0-9_]*):\s*z\./gm).filter((k) => /_ENABLED$/.test(k));
  // Read straight off process.env somewhere else — a typo here fails SILENTLY.
  const raw = new Set<string>();
  const scan = (dir: string) => {
    for (const f of ls(dir)) {
      const p = join(dir, f);
      if (!/\./.test(f)) {
        scan(p);
        continue;
      }
      if (!/\.tsx?$/.test(f)) continue;
      for (const k of all(read(p), /process\.env\.([A-Z][A-Z0-9_]*_ENABLED)/g)) {
        if (!declared.includes(k)) raw.add(k);
      }
    }
  };
  scan("src");
  scan("workers");
  return { declared: declared.sort(), raw: [...raw].sort() };
}

/* ------------------------------------------------------------------ render */

function build(): string {
  const s = schema();
  const m = migrations();
  const w = scheduled();
  const t = aiTools();
  const e = evals();
  const f = flags();
  const smokes = ls("scripts").filter((x) => x.startsWith("smoke-"));

  let head = "(unknown)";
  try {
    head = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: ROOT }).toString().trim();
  } catch {
    /* not a git checkout */
  }

  const L: string[] = [];
  const p = (s = "") => L.push(s);

  p("<!-- GENERATED by scripts/gen-docs-state.ts — do not edit by hand. -->");
  p("<!-- Regenerate with: npm run docs:state -->");
  p();
  p("# STATE.generated.md — the counts");
  p();
  p("> Every count and inventory in the documentation set lives here, derived from the code.");
  p("> **No other document may state a number** — link to a section of this file instead.");
  p("> If you are about to type a count into a doc, you are in the wrong file.");
  p();
  p(`Generated from commit \`${head}\`.`);
  p();

  p("## Schema");
  p();
  p(`- **${s.tables.length}** tables · **${s.enums.length}** enums — \`src/lib/db/schema.ts\``);
  p(`- Migration head: \`${m.head}\` · **${m.count}** numbered migrations · journal entries: **${m.journal}**`);
  if (m.count !== m.journal) {
    p(`  - ⚠️ **${m.count} files vs ${m.journal} journal entries** — a migration is unjournalled.`);
  }
  p(`- Applied by hand, OUTSIDE the journal (a fresh Neon branch silently lacks these): ${m.manual.map((x) => `\`${x}\``).join(" · ")}`);
  p();
  p("<details><summary>All tables</summary>");
  p();
  p(s.tables.map((x) => `\`${x}\``).join(" · "));
  p();
  p("</details>");
  p();

  p("## Scheduled work");
  p();
  p(`- **${w.jobs.length}** Railway supervisor jobs — \`workers/supervisor.ts\``);
  p(`- **${w.crons.length}** Vercel crons — \`vercel.json\``);
  if (w.doubled.length) {
    p(`- ⚠️ **Triggered from BOTH schedulers** (so the route fires twice per window): ${w.doubled.map((x) => `\`${x}\``).join(", ")}`);
    p("  Harmless *only* because those routes are idempotent — `shift-reminders` dedupes per");
    p("  (placement, tier) and `clockout-digest` throttles to one send a day. Keep them that way.");
  }
  p();
  p("| Job | Schedule (Europe/Amsterdam) | Where |");
  p("| --- | --- | --- |");
  for (const j of w.jobs) p(`| \`${j.name}\` | \`${j.schedule}\` | Railway |`);
  for (const c of w.crons) p(`| \`${c.path}\` | \`${c.schedule}\` | Vercel |`);
  p();

  p("## AI tools");
  p();
  p(`- **${t.defined}** tools defined via \`defineTool\` across \`src/lib/ai/tools/\``);
  p(`- Registries: **${t.owner}** owner (\`ALL_TOOLS\`) · **${t.chef}** chef · **${t.client}** klant (\`portal-index.ts\`)`);
  p(`- By risk tier: ${Object.entries(t.byRisk).sort().map(([k, v]) => `**${v}** ${k}`).join(" · ")}`);
  p("  - `read` needs no confirmation; `outbound` and `financial` require an HMAC confirm token.");
  p();
  p("<details><summary>All tool names</summary>");
  p();
  p(t.names.map((x) => `\`${x}\``).join(" · "));
  p();
  p("</details>");
  p();

  p("## Evals & smokes");
  p();
  p(`- **${e.total}** eval cases — ${Object.entries(e.counts).map(([k, v]) => `${v} ${k}`).join(" · ")} (\`scripts/eval-ai.mts\`)`);
  p("  - These score **tool routing only** — `brain.plan` is called, no tool is executed. A tool that");
  p("    throws on every call still scores a pass. Result quality is not measured anywhere.");
  if (e.dupes.length) p(`  - ⚠️ Duplicate case ids (one masks the other in the log): ${e.dupes.map((x) => `\`${x}\``).join(", ")}`);
  p(`- **${smokes.length}** smoke scripts — \`scripts/smoke-*\``);
  p();

  p("## Feature flags");
  p();
  p(`- **${f.declared.length}** \`*_ENABLED\` flags declared in \`src/lib/env.ts\` (validated by zod — a typo fails loudly).`);
  p();
  p(f.declared.map((x) => `\`${x}\``).join(" · "));
  p();
  if (f.raw.length) {
    p(`- ⚠️ **${f.raw.length}** more are read straight off \`process.env\` and are NOT in the zod schema.`);
    p("  A typo in one of these fails **silently** — the feature just stays off forever.");
    p();
    p(f.raw.map((x) => `\`${x}\``).join(" · "));
    p();
  }
  p("> Which flags are ON **in production** is not derivable from the code — that lives in MEMORY.md.");
  p();

  return L.join("\n");
}

/* -------------------------------------------------------------------- main */

const out = build();

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  // Ignore the commit line — it changes every commit and is not a staleness signal.
  const strip = (x: string) => x.replace(/^Generated from commit .*$/m, "");
  if (strip(current) !== strip(out)) {
    console.error("✗ docs/STATE.generated.md is out of date. Run: npm run docs:state");
    process.exit(1);
  }
  console.log("✓ docs/STATE.generated.md is up to date");
} else {
  writeFileSync(OUT, out);
  console.log(`✓ wrote docs/STATE.generated.md`);
}
